name: Deploy BrickBreaker WebGL via FLAPFLOP

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    name: Build & Deploy Unity WebGL
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Toon inhoud van de Build-folder
        run: dir Build
        shell: cmd

      - name: Upload WebGL build naar Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: Build

  deploy:
    name: Deploy naar GitHub Pages
    needs: build
    runs-on: [self-hosted, Windows, X64]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
